### ISSUE TITLE
I'm trying to adapt your code to make a simple blink led in stm32f469 disco

### ISSUE THREAD

**Issue by neuberfran** [aholzbaur/rust-stm32f4-disco-blinky#5]
Hi,

https://dev.to/apollolabsbin/stm32f4-embedded-rust-at-the-hal-button-controlled-blinking-by-timer-polling-3bno

I'm trying to adapt your code to the code in the link above to make a simple blink led. I'm getting the issues below and I say any help from you is welcome
```
Compiling stm32f4xx-hal v0.11.1
error[E0432]: unresolved import `fugit`
 --> src/main.rs:6:5
  |
6 | use fugit::{Duration, ExtU32};
  |     ^^^^^ use of undeclared crate or module `fugit`

error[E0689]: can't call method `MHz` on ambiguous numeric type `{integer}`
  --> src/main.rs:20:37
   |
20 |     let clocks = rcc.cfgr.use_hse(8.MHz()).freeze();
   |                                     ^^^
   |
help: you must specify a concrete type for this numeric value, like `i32`
   |
20 |     let clocks = rcc.cfgr.use_hse(8_i32.MHz()).freeze();
   |                                   ~~~~~

error[E0599]: no method named `counter_ms` found for struct `TIM1` in the current scope
  --> src/main.rs:40:31
   |
40 |     let mut counter = dp.TIM1.counter_ms(&clocks);
   |                               ^^^^^^^^^^ method not found in `TIM1`

Some errors have detailed explanations: E0432, E0599, E0689.
For more information about an error, try `rustc --explain E0432`.
error: could not compile `rust-stm32f4-disco-blinky` due to 3 previous errors
```
![Screenshot from 2023-08-03 11-55-24](https://github.com/aholzbaur/rust-stm32f4-disco-blinky/assets/38701397/7a47d690-e119-4d2a-9663-06a73de1d1a9)

**Comment by apollolabsdev** [comment]
Hello @neuberfran, please check that your cargo.toml is matching. There are two issues, one is that the fugit crate is not imported. Second, it seems that you are running on a different/older version of the HAL crate. My code was on "0.13.1", it seems you are on "0.11.1".

**Comment by neuberfran** [comment]
To resolve this issue I referred to this video of mine on the channel: https://www.youtube.com/watch?v=4rV624d6xv8

In the st community forum they told me (as shown in the photo below) that pa1 is equal to d3 in the arduino pinout of the stm32f469 disco kit.

I also started using cargo flash --release --chip stm32f469 ih6 as per the link below:
https://probe.rs/docs/tools/cargo-flash/

https://www.youtube.com/watch?v=TKCirpm_SSw

Note: 1) I looked at the datasheet and I still don't know why pa1 is equal to d3
2) I change Cargo.toml in [dependencies.stm32f4xx-hal]
version = "0.11.1" to "0.13.1"

![image (1)](https://github.com/aholzbaur/rust-stm32f4-disco-blinky/assets/38701397/734bbef7-cb95-437a-b005-eec37e5e3176)

**Comment by apollolabsdev** [comment]
The response by the ST community is correct. For the board you are using PA1 is mapped to D3. You need to refer to the user manual of your board (UM1932) for the Arduino connector mappings. A screenshot is shown below.

<img width="562" alt="Screenshot 2023-08-09 at 8 16 11 AM" src="https://github.com/aholzbaur/rust-stm32f4-disco-blinky/assets/104051566/ad04ad39-6ae1-44b3-9adb-2d459f2ab3b7">
